Log:
  Chat: true
  PM: true
  Shutdown: true
  Startup: true
  Player Join: false
  Player Quit: false
  Commands: false
File:
  Location: "logs/chat/"
  File Per Day: true
Format:
  Chat: "[%time%] %displayname% (%playername%) >> %message%"