name: SimpleChatLog
description: SimpleChatLog is a plugin which will allow you to log specific items how you want them to be logged
main: com.connorlinfoot.simplechatlog.SimpleChatLog
version: 1.4-SNAPSHOT
commands:
  scl:
    description: SimpleChatLog
permissions:
  simplechatlog.reload:
    default: op
