name: SimpleChatLog
description: SimpleChatLog - This is a message added in and hopefully built with Jenkins and Maven
main: com.connorlinfoot.simplechatlog.SimpleChatLog
version: 1.3
commands:
  scl:
    description: SimpleChatLog
permissions:
  simplechatlog.reload:
    default: op
